import Head from "next/head";
import Image from "next/image";
import { BsSearch } from "react-icons/bs";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>mxt nft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input type="search" placeholder="Search" name="" id="" />
        <BsSearch className={styles.main1} />
        <video autoPlay style={{ width: "25px", height: "35px" }}>
          <source src="/main.gif" />
        </video>
        <button className={styles.btnNew}>Sign Up</button>
        <Image
          className={styles.im2}
          src="/bitcoin.png"
          width={50}
          height={50}
        />
        <Image className={styles.im3} src="/th.jpg" height={60} width={40} />
      </main>
      <div className={styles.container - 1}>
        <h1 className={styles.mainOne}>Discover A New Era Of Cryptocurrency</h1>

        <p className={styles.description}>
          met nft the primier marketplace for NFT, which are digital items you
          can truly own. Digital items have existed for a long time, but never
          like this. eg: movies,musics,scripts etc..
        </p>

        <button className={styles.btn1}>Get Started</button>
      </div>
    </div>
  );
}
